# Informacion de las monedas seleccionadas

In [43]:
from pycoingecko import CoinGeckoAPI
from datetime import datetime
import matplotlib.pyplot as plt
import time
import pandas as pd
import myFunctions

In [44]:
cg = CoinGeckoAPI()

In [45]:
start_time = myFunctions.unix_time(2000, 1, 1, 0, 0)
end_time = myFunctions.unix_time(2023, 8, 22, 0, 0)

# bitcoin

In [46]:
bitcoin_ohlc = myFunctions.coin_ohlc("bitcoin")

bitcoin_coin_market_data = myFunctions.coin_market_chart_data("bitcoin", start_time, end_time)
bitcoin_market_data_df = myFunctions.get_coin_market_dataframe(bitcoin_coin_market_data)
bitcoin_market_data_df['id'] = 'bitcoin'

# Convertir la columna 'prices' a tipo float
bitcoin_market_data_df['prices'] = bitcoin_market_data_df['prices'].astype(float)
bitcoin_market_data_df['market_caps'] = bitcoin_market_data_df['market_caps'].astype(float)
bitcoin_market_data_df['total_volumes'] = bitcoin_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
bitcoin_market_data_df['price_diff'] = bitcoin_market_data_df['prices'] - bitcoin_market_data_df['prices'].shift(1)
bitcoin_market_data_df['market_caps_diff'] = bitcoin_market_data_df['market_caps'] - bitcoin_market_data_df['market_caps'].shift(1)
bitcoin_market_data_df['total_volumes_diff'] = bitcoin_market_data_df['total_volumes'] - bitcoin_market_data_df['total_volumes'].shift(1)
bitcoin_market_data_df["returns"] = bitcoin_market_data_df["price_diff"] / 100


# Convertir las columnas de fecha a tipo datetime
bitcoin_market_data_df['timestamp'] = pd.to_datetime(bitcoin_market_data_df['timestamp'])
bitcoin_ohlc['date'] = pd.to_datetime(bitcoin_ohlc['date'])

# Unir los DataFrames utilizando merge
bitcoin_df = pd.merge(bitcoin_market_data_df, bitcoin_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
bitcoin_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
bitcoin_df = bitcoin_df[new_order]

# Exportar DataFrame a un archivo CSV
bitcoin_df.to_csv('../Dataframes/bitcoin_df.csv', index=False)

bitcoin_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2013-04-30,bitcoin,135.30,-6.66,-0.0666,1.501657e+09,-7.337451e+07,0.000000e+00,0.000000e+00,135.30,141.96,135.30
1,2013-05-03,bitcoin,91.01,-12.42,-0.1242,1.011066e+09,-1.376012e+08,0.000000e+00,0.000000e+00,117.00,117.00,91.01
2,2013-05-07,bitcoin,106.40,-11.93,-0.1193,1.183766e+09,-1.322258e+08,0.000000e+00,0.000000e+00,111.25,118.33,106.40
3,2013-05-11,bitcoin,113.01,-5.77,-0.0577,1.259239e+09,-6.375010e+07,0.000000e+00,0.000000e+00,112.64,118.78,112.64
4,2013-05-15,bitcoin,114.16,-0.34,-0.0034,1.273850e+09,-3.429307e+06,0.000000e+00,0.000000e+00,114.71,117.18,114.16
...,...,...,...,...,...,...,...,...,...,...,...,...
977,2023-08-03,bitcoin,29146.64,-390.47,-3.9047,5.670747e+11,-5.334220e+09,1.926632e+10,3.976396e+09,29233.14,29537.11,29146.64
978,2023-08-07,bitcoin,29044.20,-2.60,-0.0260,5.649479e+11,-2.219937e+07,5.360284e+09,2.497485e+07,29176.15,29176.15,29044.20
979,2023-08-11,bitcoin,29423.82,-161.67,-1.6167,5.724142e+11,-3.121209e+09,8.106254e+09,-6.527057e+09,29178.15,29779.56,29178.15
980,2023-08-15,bitcoin,29400.59,115.62,1.1562,5.722427e+11,2.555605e+09,1.240836e+10,7.653135e+09,29396.85,29412.14,29284.97
981,2023-08-19,bitcoin,26042.84,-458.75,-4.5875,5.068158e+11,-9.211102e+09,1.806235e+10,-1.190323e+10,29170.49,29170.49,26042.84

# Ethereum

In [47]:
ethereum_ohlc = myFunctions.coin_ohlc("ethereum")

ethereum_coin_market_data = myFunctions.coin_market_chart_data("ethereum", start_time, end_time)
ethereum_market_data_df = myFunctions.get_coin_market_dataframe(ethereum_coin_market_data)

ethereum_market_data_df['id'] = 'ethereum'
# Convertir la columna 'prices' a tipo float
ethereum_market_data_df['prices'] = ethereum_market_data_df['prices'].astype(float)
ethereum_market_data_df['market_caps'] = ethereum_market_data_df['market_caps'].astype(float)
ethereum_market_data_df['total_volumes'] = ethereum_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
ethereum_market_data_df['price_diff'] = ethereum_market_data_df['prices'] - ethereum_market_data_df['prices'].shift(1)
ethereum_market_data_df['market_caps_diff'] = ethereum_market_data_df['market_caps'] - ethereum_market_data_df['market_caps'].shift(1)
ethereum_market_data_df['total_volumes_diff'] = ethereum_market_data_df['total_volumes'] - ethereum_market_data_df['total_volumes'].shift(1)
ethereum_market_data_df["returns"] = ethereum_market_data_df["price_diff"] / 100


# Convertir las columnas de fecha a tipo datetime
ethereum_market_data_df['timestamp'] = pd.to_datetime(ethereum_market_data_df['timestamp'])
ethereum_ohlc['date'] = pd.to_datetime(ethereum_ohlc['date'])

# Unir los DataFrames utilizando merge
ethereum_df = pd.merge(ethereum_market_data_df, ethereum_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
ethereum_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
ethereum_df = ethereum_df[new_order]

# Exportar DataFrame a un archivo CSV
ethereum_df.to_csv('../Dataframes/ethereum_df.csv', index=False)

ethereum_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2015-08-07,ethereum,2.83,NaN,NaN,0.000000e+00,NaN,9.062200e+04,NaN,2.83,2.83,2.83
1,2015-08-11,ethereum,1.07,0.38,0.0038,6.453901e+07,2.298270e+07,1.518998e+06,1.118534e+06,1.33,1.33,0.69
2,2015-08-15,ethereum,1.67,-0.16,-0.0016,1.012152e+08,-9.340067e+06,2.519633e+06,-1.835985e+06,1.26,1.83,1.26
3,2015-08-19,ethereum,1.25,-0.03,-0.0003,9.092070e+07,-2.037162e+06,1.537201e+06,-1.588126e+05,1.48,1.48,1.20
4,2015-08-23,ethereum,1.36,-0.02,-0.0002,9.848800e+07,-1.820762e+06,1.610696e+06,6.961072e+05,1.48,1.48,1.36
...,...,...,...,...,...,...,...,...,...,...,...,...
761,2023-08-03,ethereum,1838.01,-31.74,-0.3174,2.209365e+11,-5.015559e+09,8.178850e+09,-8.119231e+08,1857.28,1869.75,1838.01
762,2023-08-07,ethereum,1826.71,-8.36,-0.0836,2.195340e+11,-9.530325e+08,2.992818e+09,4.046865e+07,1835.70,1835.70,1826.71
763,2023-08-11,ethereum,1850.88,-5.01,-0.0501,2.224113e+11,-5.811692e+08,3.733538e+09,-2.276566e+09,1826.93,1856.84,1826.93
764,2023-08-15,ethereum,1843.51,4.00,0.0400,2.215642e+11,6.159115e+08,4.495325e+09,8.529002e+08,1847.54,1848.51,1839.51
765,2023-08-19,ethereum,1660.68,-15.18,-0.1518,1.993229e+11,-2.160098e+09,1.185691e+10,-9.105864e+09,1826.91,1826.91,1660.68

# Tether

In [48]:
tether_ohlc = myFunctions.coin_ohlc("tether")

tether_coin_market_data = myFunctions.coin_market_chart_data("tether", start_time, end_time)
tether_market_data_df = myFunctions.get_coin_market_dataframe(tether_coin_market_data)

tether_market_data_df['id'] = 'tether'
# Convertir la columna 'prices' a tipo float
tether_market_data_df['prices'] = tether_market_data_df['prices'].astype(float)
tether_market_data_df['market_caps'] = tether_market_data_df['market_caps'].astype(float)
tether_market_data_df['total_volumes'] = tether_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
tether_market_data_df['price_diff'] = tether_market_data_df['prices'] - tether_market_data_df['prices'].shift(1)
tether_market_data_df['market_caps_diff'] = tether_market_data_df['market_caps'] - tether_market_data_df['market_caps'].shift(1)
tether_market_data_df['total_volumes_diff'] = tether_market_data_df['total_volumes'] - tether_market_data_df['total_volumes'].shift(1)
tether_market_data_df["returns"] = tether_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
tether_market_data_df['timestamp'] = pd.to_datetime(tether_market_data_df['timestamp'])
tether_ohlc['date'] = pd.to_datetime(tether_ohlc['date'])

# Unir los DataFrames utilizando merge
tether_df = pd.merge(tether_market_data_df, tether_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
tether_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
tether_df = tether_df[new_order]

# Exportar DataFrame a un archivo CSV
tether_df.to_csv('../Dataframes/tether_df.csv', index=False)

tether_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2015-03-07,tether,1.0,0.0,0.0,2.516000e+05,0.000000e+00,5.819600e+04,5.814600e+04,1.0,1.0,1.0
1,2015-03-11,tether,1.0,0.0,0.0,2.516000e+05,0.000000e+00,4.600000e+01,-4.996000e+04,1.0,1.0,1.0
2,2015-03-15,tether,1.0,0.0,0.0,2.516000e+05,0.000000e+00,1.512400e+04,-2.582000e+03,1.0,1.0,1.0
3,2015-03-19,tether,1.0,0.0,0.0,2.516000e+05,0.000000e+00,8.570000e+02,7.990000e+02,1.0,1.0,1.0
4,2015-03-23,tether,1.0,0.0,0.0,2.516000e+05,0.000000e+00,6.500000e+01,-1.000000e+00,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
798,2023-08-03,tether,1.0,0.0,0.0,8.388853e+10,7.221443e+07,2.364385e+10,-1.733185e+09,1.0,1.0,1.0
799,2023-08-07,tether,1.0,0.0,0.0,8.375169e+10,-6.528705e+07,1.134571e+10,2.713086e+09,1.0,1.0,1.0
800,2023-08-11,tether,1.0,0.0,0.0,8.344563e+10,-5.131214e+07,1.089010e+10,-7.877206e+09,1.0,1.0,1.0
801,2023-08-15,tether,1.0,0.0,0.0,8.332348e+10,2.019514e+07,1.279237e+10,3.538228e+09,1.0,1.0,1.0
802,2023-08-19,tether,1.0,0.0,0.0,8.284635e+10,4.415652e+08,2.847330e+10,-1.054599e+10,1.0,1.0,1.0

# Binancecoin

In [49]:
binancecoin_ohlc = myFunctions.coin_ohlc("binancecoin")

binancecoin_coin_market_data = myFunctions.coin_market_chart_data("binancecoin", start_time, end_time)
binancecoin_market_data_df = myFunctions.get_coin_market_dataframe(binancecoin_coin_market_data)

binancecoin_market_data_df['id'] = 'binancecoin'
# Convertir la columna 'prices' a tipo float
binancecoin_market_data_df['prices'] = binancecoin_market_data_df['prices'].astype(float)
binancecoin_market_data_df['market_caps'] = binancecoin_market_data_df['market_caps'].astype(float)
binancecoin_market_data_df['total_volumes'] = binancecoin_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
binancecoin_market_data_df['price_diff'] = binancecoin_market_data_df['prices'] - binancecoin_market_data_df['prices'].shift(1)
binancecoin_market_data_df['market_caps_diff'] = binancecoin_market_data_df['market_caps'] - binancecoin_market_data_df['market_caps'].shift(1)
binancecoin_market_data_df['total_volumes_diff'] = binancecoin_market_data_df['total_volumes'] - binancecoin_market_data_df['total_volumes'].shift(1)
binancecoin_market_data_df["returns"] = binancecoin_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
binancecoin_market_data_df['timestamp'] = pd.to_datetime(binancecoin_market_data_df['timestamp'])
binancecoin_ohlc['date'] = pd.to_datetime(binancecoin_ohlc['date'])

# Unir los DataFrames utilizando merge
binancecoin_df = pd.merge(binancecoin_market_data_df, binancecoin_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
binancecoin_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
binancecoin_df = binancecoin_df[new_order]

# Exportar DataFrame a un archivo CSV
binancecoin_df.to_csv('../Dataframes/binancecoin_df.csv', index=False)

binancecoin_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2017-09-19,binancecoin,0.17,0.00,0.0000,1.683342e+07,-5.157049e+05,3.880000e+00,-2.120000e+00,0.11,0.17,0.11
1,2017-09-23,binancecoin,0.09,0.00,0.0000,8.828963e+06,-5.923349e+05,7.900000e-01,-1.350900e+02,0.17,0.17,0.09
2,2017-09-27,binancecoin,0.12,0.03,0.0003,1.150551e+07,2.539733e+06,5.955000e+01,4.136000e+01,0.09,0.12,0.09
3,2017-09-30,binancecoin,0.17,0.04,0.0004,1.719116e+07,3.973836e+06,2.046400e+02,2.020200e+02,0.14,0.17,0.13
4,2017-10-03,binancecoin,0.12,0.01,0.0001,1.244324e+07,1.655874e+06,4.209000e+01,2.765000e+01,0.10,0.12,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...
559,2023-08-03,binancecoin,240.38,-7.05,-0.0705,3.703518e+10,-9.622428e+08,7.502332e+08,-1.041493e+08,241.19,247.43,240.38
560,2023-08-07,binancecoin,242.57,-0.31,-0.0031,3.732460e+10,-4.325379e+07,3.723593e+08,1.208226e+08,241.14,242.88,241.14
561,2023-08-11,binancecoin,241.23,-2.78,-0.0278,3.711219e+10,-4.296112e+08,3.390474e+08,-6.245683e+07,241.74,245.18,241.23
562,2023-08-15,binancecoin,240.36,0.33,0.0033,3.697023e+10,5.641108e+07,3.232128e+08,9.244901e+07,239.60,240.36,239.60
563,2023-08-19,binancecoin,215.97,-1.83,-0.0183,3.322978e+10,-3.227947e+08,6.146381e+08,-3.316293e+08,236.61,236.61,215.97

# Ripple

In [50]:
ripple_ohlc = myFunctions.coin_ohlc("ripple")

ripple_coin_market_data = myFunctions.coin_market_chart_data("ripple", start_time, end_time)
ripple_market_data_df = myFunctions.get_coin_market_dataframe(ripple_coin_market_data)

ripple_market_data_df['id'] = 'ripple'
# Convertir la columna 'prices' a tipo float
ripple_market_data_df['prices'] = ripple_market_data_df['prices'].astype(float)
ripple_market_data_df['market_caps'] = ripple_market_data_df['market_caps'].astype(float)
ripple_market_data_df['total_volumes'] = ripple_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
ripple_market_data_df['price_diff'] = ripple_market_data_df['prices'] - ripple_market_data_df['prices'].shift(1)
ripple_market_data_df['market_caps_diff'] = ripple_market_data_df['market_caps'] - ripple_market_data_df['market_caps'].shift(1)
ripple_market_data_df['total_volumes_diff'] = ripple_market_data_df['total_volumes'] - ripple_market_data_df['total_volumes'].shift(1)
ripple_market_data_df["returns"] = ripple_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
ripple_market_data_df['timestamp'] = pd.to_datetime(ripple_market_data_df['timestamp'])
ripple_ohlc['date'] = pd.to_datetime(ripple_ohlc['date'])

# Unir los DataFrames utilizando merge
ripple_df = pd.merge(ripple_market_data_df, ripple_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
ripple_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
ripple_df = ripple_df[new_order]

# Exportar DataFrame a un archivo CSV
ripple_df.to_csv('../Dataframes/ripple_df.csv', index=False)

ripple_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2013-08-07,ripple,0.00,0.00,0.0000,3.507144e+07,-1.429188e+06,0.000000e+00,0.000000e+00,0.01,0.01,0.00
1,2013-08-11,ripple,0.00,0.00,0.0000,3.418044e+07,4.201340e+05,0.000000e+00,0.000000e+00,0.00,0.00,0.00
2,2013-08-15,ripple,0.00,0.00,0.0000,2.601450e+07,-4.052091e+06,0.000000e+00,0.000000e+00,0.00,0.00,0.00
3,2013-08-19,ripple,0.01,0.00,0.0000,4.346559e+07,-4.986875e+06,0.000000e+00,0.000000e+00,0.00,0.01,0.00
4,2013-08-23,ripple,0.01,0.00,0.0000,4.014643e+07,-6.503702e+06,0.000000e+00,0.000000e+00,0.01,0.01,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...
950,2023-08-03,ripple,0.68,-0.03,-0.0003,3.612055e+10,-1.057130e+09,1.053596e+09,-4.676914e+08,0.70,0.71,0.68
951,2023-08-07,ripple,0.62,-0.01,-0.0001,3.276840e+10,-3.584649e+08,7.710698e+08,-2.311294e+08,0.66,0.66,0.62
952,2023-08-11,ripple,0.63,-0.01,-0.0001,3.342676e+10,-5.506590e+08,1.063358e+09,-4.350368e+08,0.62,0.64,0.62
953,2023-08-15,ripple,0.63,0.00,0.0000,3.352678e+10,5.058452e+08,9.673053e+08,3.463654e+08,0.63,0.63,0.63
954,2023-08-19,ripple,0.51,0.01,0.0001,2.667860e+10,1.238305e+07,1.918959e+09,-2.761486e+08,0.61,0.61,0.50

# usd-coin

In [51]:
usd_coin_ohlc = myFunctions.coin_ohlc("usd-coin")

usd_coin_coin_market_data = myFunctions.coin_market_chart_data("usd-coin", start_time, end_time)
usd_coin_market_data_df = myFunctions.get_coin_market_dataframe(usd_coin_coin_market_data)

usd_coin_market_data_df['id'] = 'usd-coin'
# Convertir la columna 'prices' a tipo float
usd_coin_market_data_df['prices'] = usd_coin_market_data_df['prices'].astype(float)
usd_coin_market_data_df['market_caps'] = usd_coin_market_data_df['market_caps'].astype(float)
usd_coin_market_data_df['total_volumes'] = usd_coin_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
usd_coin_market_data_df['price_diff'] = usd_coin_market_data_df['prices'] - usd_coin_market_data_df['prices'].shift(1)
usd_coin_market_data_df['market_caps_diff'] = usd_coin_market_data_df['market_caps'] - usd_coin_market_data_df['market_caps'].shift(1)
usd_coin_market_data_df['total_volumes_diff'] = usd_coin_market_data_df['total_volumes'] - usd_coin_market_data_df['total_volumes'].shift(1)
usd_coin_market_data_df["returns"] = usd_coin_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
usd_coin_market_data_df['timestamp'] = pd.to_datetime(usd_coin_market_data_df['timestamp'])
usd_coin_ohlc['date'] = pd.to_datetime(usd_coin_ohlc['date'])

# Unir los DataFrames utilizando merge
usd_coin_df = pd.merge(usd_coin_market_data_df, usd_coin_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
usd_coin_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
usd_coin_df = usd_coin_df[new_order]

# Exportar DataFrame a un archivo CSV
usd_coin_df.to_csv('../Dataframes/usd_coin_df.csv', index=False)

usd_coin_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2018-10-07,usd-coin,1.00,0.00,0.0000,0.000000e+00,0.000000e+00,4.932469e+04,2.906998e+04,1.01,1.01,1.00
1,2018-10-11,usd-coin,1.00,0.00,0.0000,0.000000e+00,0.000000e+00,4.878948e+04,6.976980e+03,1.00,1.00,1.00
2,2018-10-15,usd-coin,1.02,0.01,0.0001,0.000000e+00,0.000000e+00,1.140475e+05,-1.975891e+04,1.01,1.02,1.01
3,2018-10-19,usd-coin,1.02,-0.01,-0.0001,0.000000e+00,-2.459024e+07,5.770299e+05,-1.242982e+06,1.04,1.04,1.02
4,2018-10-23,usd-coin,1.02,-0.01,-0.0001,0.000000e+00,0.000000e+00,4.756981e+05,2.644474e+05,1.02,1.03,1.02
...,...,...,...,...,...,...,...,...,...,...,...,...
459,2023-08-03,usd-coin,1.00,0.00,0.0000,2.619386e+10,-1.264121e+08,4.492430e+09,-8.336773e+08,1.00,1.00,1.00
460,2023-08-07,usd-coin,1.00,0.00,0.0000,2.604314e+10,2.781969e+06,1.874549e+09,1.988404e+08,1.00,1.00,1.00
461,2023-08-11,usd-coin,1.00,0.00,0.0000,2.615260e+10,-1.316599e+08,2.203564e+09,-8.133757e+08,1.00,1.00,1.00
462,2023-08-15,usd-coin,1.00,0.00,0.0000,2.600436e+10,-1.762234e+08,2.461886e+09,7.800588e+08,1.00,1.00,1.00
463,2023-08-19,usd-coin,1.00,0.00,0.0000,2.599099e+10,-2.072892e+07,4.443167e+09,2.689318e+07,1.00,1.00,1.00

# staked-ether

In [52]:
staked_ether_ohlc = myFunctions.coin_ohlc("staked-ether")

staked_ether_coin_market_data = myFunctions.coin_market_chart_data("staked-ether", start_time, end_time)
staked_ether_market_data_df = myFunctions.get_coin_market_dataframe(staked_ether_coin_market_data)

staked_ether_market_data_df['id'] = 'staked-ether'
# Convertir la columna 'prices' a tipo float
staked_ether_market_data_df['prices'] = staked_ether_market_data_df['prices'].astype(float)
staked_ether_market_data_df['market_caps'] = staked_ether_market_data_df['market_caps'].astype(float)
staked_ether_market_data_df['total_volumes'] = staked_ether_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
staked_ether_market_data_df['price_diff'] = staked_ether_market_data_df['prices'] - staked_ether_market_data_df['prices'].shift(1)
staked_ether_market_data_df['market_caps_diff'] = staked_ether_market_data_df['market_caps'] - staked_ether_market_data_df['market_caps'].shift(1)
staked_ether_market_data_df['total_volumes_diff'] = staked_ether_market_data_df['total_volumes'] - staked_ether_market_data_df['total_volumes'].shift(1)
staked_ether_market_data_df["returns"] = staked_ether_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
staked_ether_market_data_df['timestamp'] = pd.to_datetime(staked_ether_market_data_df['timestamp'])
staked_ether_ohlc['date'] = pd.to_datetime(staked_ether_ohlc['date'])

# Unir los DataFrames utilizando merge
staked_ether_df = pd.merge(staked_ether_market_data_df, staked_ether_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
staked_ether_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
staked_ether_df = staked_ether_df[new_order]

# Exportar DataFrame a un archivo CSV
staked_ether_df.to_csv('../Dataframes/staked_ether_df.csv', index=False)

staked_ether_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2020-12-23,staked-ether,617.16,0.00,0.0000,0.000000e+00,0.000000e+00,137563.03,0.00,617.16,617.16,617.16
1,2020-12-27,staked-ether,629.07,4.27,0.0427,7.530256e+06,2.455121e+05,10300.37,-35632.69,596.77,629.07,596.77
2,2020-12-31,staked-ether,722.28,-0.49,-0.0049,1.190541e+07,4.120375e+05,95848.21,-20893.23,678.10,730.42,678.10
3,2021-01-03,staked-ether,772.06,48.53,0.4853,1.320595e+07,1.082508e+06,34572.92,29468.27,733.32,772.06,723.53
4,2021-01-07,staked-ether,1173.33,59.43,0.5943,2.139665e+07,2.014801e+06,38065.92,-404512.05,977.57,1173.33,966.90
...,...,...,...,...,...,...,...,...,...,...,...,...
248,2023-08-03,staked-ether,1836.06,-43.16,-0.4316,1.462211e+10,-2.229318e+08,43552961.49,-28931698.29,1857.55,1879.22,1836.06
249,2023-08-07,staked-ether,1826.24,-8.86,-0.0886,1.458317e+10,-5.758513e+07,26173043.14,19801449.17,1835.27,1835.27,1826.24
250,2023-08-11,staked-ether,1849.45,-5.91,-0.0591,1.489187e+10,8.837115e+06,22500456.48,-10745133.37,1821.72,1856.80,1821.72
251,2023-08-15,staked-ether,1842.55,4.64,0.0464,1.493220e+10,5.506370e+07,5027849.07,1411037.18,1846.30,1846.71,1837.91
252,2023-08-19,staked-ether,1659.99,-18.54,-0.1854,1.356056e+10,-1.397835e+08,25265068.44,-2288588.90,1826.36,1826.36,1659.99

# cardano

In [53]:
cardano_ohlc = myFunctions.coin_ohlc("cardano")

cardano_coin_market_data = myFunctions.coin_market_chart_data("cardano", start_time, end_time)
cardano_market_data_df = myFunctions.get_coin_market_dataframe(cardano_coin_market_data)

cardano_market_data_df['id'] = 'cardano'
# Convertir la columna 'prices' a tipo float
cardano_market_data_df['prices'] = cardano_market_data_df['prices'].astype(float)
cardano_market_data_df['market_caps'] = cardano_market_data_df['market_caps'].astype(float)
cardano_market_data_df['total_volumes'] = cardano_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
cardano_market_data_df['price_diff'] = cardano_market_data_df['prices'] - cardano_market_data_df['prices'].shift(1)
cardano_market_data_df['market_caps_diff'] = cardano_market_data_df['market_caps'] - cardano_market_data_df['market_caps'].shift(1)
cardano_market_data_df['total_volumes_diff'] = cardano_market_data_df['total_volumes'] - cardano_market_data_df['total_volumes'].shift(1)
cardano_market_data_df["returns"] = cardano_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
cardano_market_data_df['timestamp'] = pd.to_datetime(cardano_market_data_df['timestamp'])
cardano_ohlc['date'] = pd.to_datetime(cardano_ohlc['date'])

# Unir los DataFrames utilizando merge
cardano_df = pd.merge(cardano_market_data_df, cardano_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
cardano_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
cardano_df = cardano_df[new_order]

# Exportar DataFrame a un archivo CSV
cardano_df.to_csv('../Dataframes/cardano_df.csv', index=False)

cardano_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2017-10-19,cardano,0.03,0.00,0.0000,6.956220e+08,-3.993860e+05,2.815156e+06,463477.85,0.03,0.03,0.03
1,2017-10-23,cardano,0.03,0.00,0.0000,6.752738e+08,-4.539603e+07,3.505127e+06,603250.42,0.03,0.03,0.03
2,2017-10-27,cardano,0.03,0.00,0.0000,6.873168e+08,-2.120287e+06,2.569634e+06,200233.54,0.03,0.03,0.03
3,2017-10-31,cardano,0.03,0.00,0.0000,7.843223e+08,4.837182e+07,7.251417e+06,3456663.93,0.03,0.03,0.03
4,2017-11-03,cardano,0.02,0.00,0.0000,5.908631e+08,3.808294e+07,3.029090e+06,-2926161.61,0.02,0.02,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...
551,2023-08-03,cardano,0.30,-0.01,-0.0001,1.048192e+10,-3.436780e+08,2.082139e+08,-34328266.25,0.31,0.31,0.30
552,2023-08-07,cardano,0.29,0.00,0.0000,1.021785e+10,-6.297062e+07,1.507591e+08,-6770456.48,0.29,0.29,0.29
553,2023-08-11,cardano,0.30,0.00,0.0000,1.037526e+10,-1.874160e+08,1.794778e+08,-16040871.41,0.29,0.30,0.29
554,2023-08-15,cardano,0.29,0.00,0.0000,1.018196e+10,4.691557e+07,1.298745e+08,4768173.24,0.29,0.29,0.29
555,2023-08-19,cardano,0.26,0.01,0.0001,9.235486e+09,3.169831e+08,2.651095e+08,-75534069.98,0.28,0.28,0.25

# dogecoin

In [54]:
dogecoin_ohlc = myFunctions.coin_ohlc("dogecoin")

dogecoin_coin_market_data = myFunctions.coin_market_chart_data("dogecoin", start_time, end_time)
dogecoin_market_data_df = myFunctions.get_coin_market_dataframe(dogecoin_coin_market_data)

dogecoin_market_data_df['id'] = 'dogecoin'
# Convertir la columna 'prices' a tipo float
dogecoin_market_data_df['prices'] = dogecoin_market_data_df['prices'].astype(float)
dogecoin_market_data_df['market_caps'] = dogecoin_market_data_df['market_caps'].astype(float)
dogecoin_market_data_df['total_volumes'] = dogecoin_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
dogecoin_market_data_df['price_diff'] = dogecoin_market_data_df['prices'] - dogecoin_market_data_df['prices'].shift(1)
dogecoin_market_data_df['market_caps_diff'] = dogecoin_market_data_df['market_caps'] - dogecoin_market_data_df['market_caps'].shift(1)
dogecoin_market_data_df['total_volumes_diff'] = dogecoin_market_data_df['total_volumes'] - dogecoin_market_data_df['total_volumes'].shift(1)
dogecoin_market_data_df["returns"] = dogecoin_market_data_df["price_diff"] / 100

# Convertir las columnas de fecha a tipo datetime
dogecoin_market_data_df['timestamp'] = pd.to_datetime(dogecoin_market_data_df['timestamp'])
dogecoin_ohlc['date'] = pd.to_datetime(dogecoin_ohlc['date'])

# Unir los DataFrames utilizando merge
dogecoin_df = pd.merge(dogecoin_market_data_df, dogecoin_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
dogecoin_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
dogecoin_df = dogecoin_df[new_order]

# Exportar DataFrame a un archivo CSV
dogecoin_df.to_csv('../Dataframes/dogecoin_df.csv', index=False)

dogecoin_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2013-12-15,dogecoin,0.00,NaN,NaN,3.488670e+06,NaN,0.000000e+00,NaN,0.00,0.00,0.00
1,2013-12-19,dogecoin,0.00,0.00,0.0000,4.299422e+06,2.107435e+06,0.000000e+00,0.000000e+00,0.00,0.00,0.00
2,2013-12-23,dogecoin,0.00,0.00,0.0000,4.022744e+06,-6.168220e+05,0.000000e+00,0.000000e+00,0.00,0.00,0.00
3,2013-12-27,dogecoin,0.00,0.00,0.0000,8.200082e+06,1.853080e+05,4.086430e+05,4.086430e+05,0.00,0.00,0.00
4,2013-12-31,dogecoin,0.00,0.00,0.0000,7.902574e+06,3.273450e+05,3.079710e+05,-1.905100e+04,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
917,2023-08-03,dogecoin,0.07,-0.01,-0.0001,1.041960e+10,-5.059634e+08,4.378788e+08,-1.350934e+07,0.08,0.08,0.07
918,2023-08-07,dogecoin,0.07,-0.01,-0.0001,1.041788e+10,-1.976403e+08,3.690576e+08,-1.699763e+08,0.07,0.08,0.07
919,2023-08-11,dogecoin,0.08,0.00,0.0000,1.064195e+10,4.517115e+07,3.993660e+08,2.961785e+07,0.07,0.08,0.07
920,2023-08-15,dogecoin,0.07,0.00,0.0000,1.051512e+10,1.116186e+07,4.339586e+08,1.084278e+08,0.08,0.08,0.07
921,2023-08-19,dogecoin,0.06,0.00,0.0000,8.883843e+09,2.931383e+08,5.861529e+08,-2.892601e+08,0.07,0.07,0.06

# solana

In [55]:
solana_ohlc = myFunctions.coin_ohlc("solana")

solana_coin_market_data = myFunctions.coin_market_chart_data("solana", start_time, end_time)
solana_market_data_df = myFunctions.get_coin_market_dataframe(solana_coin_market_data)

solana_market_data_df['id'] = 'solana'
# Convertir la columna 'prices' a tipo float
solana_market_data_df['prices'] = solana_market_data_df['prices'].astype(float)
solana_market_data_df['market_caps'] = solana_market_data_df['market_caps'].astype(float)
solana_market_data_df['total_volumes'] = solana_market_data_df['total_volumes'].astype(float)

# Calcular la diferencia de prices, market_cap y total_volumes entre el dÃ­a actual y el dÃ­a anterior
solana_market_data_df['price_diff'] = solana_market_data_df['prices'] - solana_market_data_df['prices'].shift(1)
solana_market_data_df['market_caps_diff'] = solana_market_data_df['market_caps'] - solana_market_data_df['market_caps'].shift(1)
solana_market_data_df['total_volumes_diff'] = solana_market_data_df['total_volumes'] - solana_market_data_df['total_volumes'].shift(1)
solana_market_data_df["returns"] = solana_market_data_df["price_diff"] / 100


# Convertir las columnas de fecha a tipo datetime
solana_market_data_df['timestamp'] = pd.to_datetime(solana_market_data_df['timestamp'])
solana_ohlc['date'] = pd.to_datetime(solana_ohlc['date'])

# Unir los DataFrames utilizando merge
solana_df = pd.merge(solana_market_data_df, solana_ohlc, left_on='timestamp', right_on='date', how='inner')

columns_to_drop = ['timestamp', "close"]
solana_df.drop(columns=columns_to_drop, inplace=True)

# Reorganizar columnas
new_order = ['date', 'id', 'prices', 'price_diff', "returns", 'market_caps', 'market_caps_diff', 'total_volumes', 'total_volumes_diff', 'open', 'high', 'low']
solana_df = solana_df[new_order]

# Exportar DataFrame a un archivo CSV
solana_df.to_csv('../Dataframes/solana_df.csv', index=False)

solana_df

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2020-04-11,solana,0.96,NaN,NaN,7.827652e+06,NaN,9.267267e+07,NaN,0.96,0.96,0.96
1,2020-04-15,solana,0.67,-0.12,-0.0012,5.306221e+06,-9.961431e+05,1.752353e+07,-2.055682e+06,0.78,0.88,0.67
2,2020-04-19,solana,0.68,0.02,0.0002,5.423066e+06,7.474231e+04,1.019932e+07,-2.771659e+04,0.64,0.69,0.64
3,2020-04-23,solana,0.68,0.11,0.0011,5.446538e+06,8.549914e+05,1.814679e+07,8.535948e+06,0.61,0.68,0.53
4,2020-04-27,solana,0.64,-0.01,-0.0001,5.137791e+06,-3.582790e+04,8.493459e+06,1.168498e+06,0.62,0.65,0.62
...,...,...,...,...,...,...,...,...,...,...,...,...
315,2023-08-03,solana,23.13,-0.80,-0.0080,9.376126e+09,-2.875034e+08,4.269454e+08,-6.984695e+06,23.76,23.93,23.13
316,2023-08-07,solana,23.16,0.53,0.0053,9.384286e+09,2.287942e+08,3.381710e+08,8.180034e+07,22.65,23.16,22.63
317,2023-08-11,solana,24.62,0.24,0.0024,9.982519e+09,8.782001e+07,3.521246e+08,-1.059151e+08,23.05,24.62,23.05
318,2023-08-15,solana,25.15,0.93,0.0093,1.021132e+10,3.717702e+08,3.880259e+08,1.098438e+08,24.58,25.15,24.22
319,2023-08-19,solana,21.33,-0.32,-0.0032,8.681696e+09,-1.516802e+08,4.122202e+08,-2.441924e+08,23.88,23.88,21.33

------------

## Separacion de dataframes por aÃ±o

se unen los dataframes y separamos por aÃ±o

In [56]:
bitcoin_df = pd.read_csv("../Dataframes/bitcoin_df.csv")
ethereum_df = pd.read_csv("../Dataframes/ethereum_df.csv")
tether_df = pd.read_csv("../Dataframes/tether_df.csv")
binancecoin_df = pd.read_csv("../Dataframes/binancecoin_df.csv")
ripple_df = pd.read_csv("../Dataframes/ripple_df.csv")
usd_coin_df = pd.read_csv("../Dataframes/usd_coin_df.csv")
staked_ether_df = pd.read_csv("../Dataframes/staked_ether_df.csv")
cardano_df = pd.read_csv("../Dataframes/cardano_df.csv")
dogecoin_df = pd.read_csv("../Dataframes/dogecoin_df.csv")
solana_df = pd.read_csv("../Dataframes/solana_df.csv")

# Concatenar todos los DataFrames en uno solo
all_df = pd.concat([bitcoin_df, ethereum_df, tether_df, binancecoin_df, ripple_df, usd_coin_df,
                    staked_ether_df, cardano_df, dogecoin_df, solana_df], ignore_index=True)

# Convertir la columna 'date' a tipo datetime
all_df["date"] = pd.to_datetime(all_df["date"])

In [57]:
# Filtrar los registros del aÃ±o 2013
coins_df_2013 = all_df[all_df["date"].dt.year == 2013]

# Exportar DataFrame a un archivo CSV
coins_df_2013.to_csv('../Dataframes/coins_df_2013.csv', index=False)

coins_df_2013

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
0,2013-04-30,bitcoin,135.30,-6.66,-0.0666,1.501657e+09,-73374511.0,0.0,0.0,135.30,141.96,135.30
1,2013-05-03,bitcoin,91.01,-12.42,-0.1242,1.011066e+09,-137601228.0,0.0,0.0,117.00,117.00,91.01
2,2013-05-07,bitcoin,106.40,-11.93,-0.1193,1.183766e+09,-132225804.0,0.0,0.0,111.25,118.33,106.40
3,2013-05-11,bitcoin,113.01,-5.77,-0.0577,1.259239e+09,-63750105.0,0.0,0.0,112.64,118.78,112.64
4,2013-05-15,bitcoin,114.16,-0.34,-0.0034,1.273850e+09,-3429307.0,0.0,0.0,114.71,117.18,114.16
...,...,...,...,...,...,...,...,...,...,...,...,...
5343,2013-12-15,dogecoin,0.00,NaN,NaN,3.488670e+06,NaN,0.0,NaN,0.00,0.00,0.00
5344,2013-12-19,dogecoin,0.00,0.00,0.0000,4.299422e+06,2107435.0,0.0,0.0,0.00,0.00,0.00
5345,2013-12-23,dogecoin,0.00,0.00,0.0000,4.022744e+06,-616822.0,0.0,0.0,0.00,0.00,0.00
5346,2013-12-27,dogecoin,0.00,0.00,0.0000,8.200082e+06,185308.0,408643.0,408643.0,0.00,0.00,0.00
5347,2013-12-31,dogecoin,0.00,0.00,0.0000,7.902574e+06,327345.0,307971.0,-19051.0,0.00,0.00,0.00

In [58]:
# Filtrar los registros del aÃ±o 2014
coins_df_2014 = all_df[all_df["date"].dt.year == 2014]

# Exportar DataFrame a un archivo CSV
coins_df_2014.to_csv('../Dataframes/coins_df_2014.csv', index=False)

In [59]:
# Filtrar los registros del aÃ±o 2015
coins_df_2015 = all_df[all_df["date"].dt.year == 2015]

# Exportar DataFrame a un archivo CSV
coins_df_2015.to_csv('../Dataframes/coins_df_2015.csv', index=False)

In [60]:
# Filtrar los registros del aÃ±o 2016
coins_df_2016 = all_df[all_df["date"].dt.year == 2016]

# Exportar DataFrame a un archivo CSV
coins_df_2016.to_csv('../Dataframes/coins_df_2016.csv', index=False)

In [61]:
# Filtrar los registros del aÃ±o 2017
coins_df_2017 = all_df[all_df["date"].dt.year == 2017]

# Exportar DataFrame a un archivo CSV
coins_df_2017.to_csv('../Dataframes/coins_df_2017.csv', index=False)

coins_df_2017

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
351,2017-01-03,bitcoin,1035.53,16.33,0.1633,1.665272e+10,2.647886e+08,4.399421e+09,-4.540678e+07,998.05,1035.53,998.05
352,2017-01-07,bitcoin,900.08,6.05,0.0605,1.448115e+10,9.887512e+07,7.496626e+09,-3.216622e+09,1130.85,1130.85,894.03
353,2017-01-11,bitcoin,784.28,-121.48,-1.2148,1.262408e+10,-1.953650e+09,5.258604e+09,2.041793e+09,908.09,908.09,784.28
354,2017-01-15,bitcoin,821.91,4.08,0.0408,1.323662e+10,6.755505e+07,9.238967e+08,-2.805830e+08,799.43,824.50,799.43
355,2017-01-19,bitcoin,896.89,22.96,0.2296,1.445143e+10,3.717489e+08,8.758585e+08,-2.721118e+08,828.31,904.15,828.31
...,...,...,...,...,...,...,...,...,...,...,...,...
5724,2017-12-15,dogecoin,0.00,0.00,0.0000,4.229113e+08,6.895447e+05,1.514466e+07,-3.272435e+06,0.00,0.00,0.00
5725,2017-12-19,dogecoin,0.01,0.00,0.0000,6.364106e+08,-8.095800e+07,3.120187e+07,-4.068077e+06,0.01,0.01,0.01
5726,2017-12-23,dogecoin,0.01,0.00,0.0000,8.565916e+08,1.577388e+08,5.739743e+07,6.034041e+06,0.01,0.01,0.01
5727,2017-12-27,dogecoin,0.01,0.00,0.0000,1.050398e+09,-6.029657e+07,4.977277e+07,-6.873847e+07,0.01,0.01,0.01
5728,2017-12-31,dogecoin,0.01,0.00,0.0000,1.078013e+09,1.377114e+08,4.690304e+07,5.978115e+05,0.01,0.01,0.01

In [62]:
# Filtrar los registros del aÃ±o 2018
coins_df_2018 = all_df[all_df["date"].dt.year == 2018]

# Exportar DataFrame a un archivo CSV
coins_df_2018.to_csv('../Dataframes/coins_df_2018.csv', index=False)

In [63]:
# Filtrar los registros del aÃ±o 2019
coins_df_2019 = all_df[all_df["date"].dt.year == 2019]

# Exportar DataFrame a un archivo CSV
coins_df_2019.to_csv('../Dataframes/coins_df_2019.csv', index=False)

In [64]:
# Filtrar los registros del aÃ±o 2020
coins_df_2020 = all_df[all_df["date"].dt.year == 2020]

# Exportar DataFrame a un archivo CSV
coins_df_2020.to_csv('../Dataframes/coins_df_2020.csv', index=False)

In [65]:
# Filtrar los registros del aÃ±o 2021
coins_df_2021 = all_df[all_df["date"].dt.year == 2021]

# Exportar DataFrame a un archivo CSV
coins_df_2021.to_csv('../Dataframes/coins_df_2021.csv', index=False)

coins_df_2021

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
732,2021-01-03,bitcoin,32163.82,2811.69,28.1169,5.978877e+11,5.229443e+10,5.727344e+10,2.318372e+10,29022.42,32163.82,29022.42
733,2021-01-07,bitcoin,36933.52,2851.31,28.5131,6.827437e+11,4.909201e+10,7.102720e+10,3.606695e+09,33008.23,36933.52,31515.58
734,2021-01-11,bitcoin,38397.90,-1898.63,-18.9863,7.140790e+11,-3.526825e+10,7.338112e+10,1.745931e+10,39547.08,40815.96,38397.90
735,2021-01-15,bitcoin,39232.75,1776.74,17.7674,7.297514e+11,3.308280e+10,5.751944e+10,-7.759500e+09,35669.91,39232.75,33938.34
736,2021-01-19,bitcoin,36595.46,791.20,7.9120,6.826472e+11,1.035531e+10,4.676903e+10,-3.980229e+09,36787.52,36787.52,35804.26
...,...,...,...,...,...,...,...,...,...,...,...,...
6425,2021-12-15,solana,161.06,5.98,0.0598,4.939887e+10,1.403522e+09,2.156901e+09,-2.154847e+08,171.84,173.74,155.08
6426,2021-12-19,solana,182.97,7.18,0.0718,5.639384e+10,2.387546e+09,1.440764e+09,-9.147669e+08,178.26,182.97,175.79
6427,2021-12-23,solana,178.57,-1.56,-0.0156,5.505805e+10,-5.127050e+08,1.635079e+09,9.558894e+07,179.94,180.13,174.37
6428,2021-12-27,solana,198.20,4.91,0.0491,6.119879e+10,1.401715e+09,1.747476e+09,4.894908e+08,190.51,198.20,190.44
6429,2021-12-31,solana,172.51,1.24,0.0124,5.326129e+10,5.346034e+08,1.379260e+09,-5.562755e+08,196.04,196.04,171.27

In [66]:
# Filtrar los registros del aÃ±o 2022
coins_df_2022 = all_df[all_df["date"].dt.year == 2022]

# Exportar DataFrame a un archivo CSV
coins_df_2022.to_csv('../Dataframes/coins_df_2022.csv', index=False)

In [67]:
# Filtrar los registros del aÃ±o 2023
coins_df_2023 = all_df[all_df["date"].dt.year == 2023]

# Exportar DataFrame a un archivo CSV
coins_df_2023.to_csv('../Dataframes/coins_df_2023.csv', index=False)

coins_df_2023

,date,id,prices,price_diff,returns,market_caps,market_caps_diff,total_volumes,total_volumes_diff,open,high,low
922,2023-01-03,bitcoin,16674.34,58.37,0.5837,3.214865e+11,1.654431e+09,1.302386e+10,3.224608e+09,16540.69,16674.34,16540.69
923,2023-01-07,bitcoin,16960.23,128.13,1.2813,3.265714e+11,2.432482e+09,1.904658e+10,4.127537e+09,16677.65,16960.23,16677.65
924,2023-01-11,bitcoin,17436.90,241.99,2.4199,3.357439e+11,4.585790e+09,2.185821e+10,-3.674545e+09,16950.86,17436.90,16950.86
925,2023-01-15,bitcoin,21019.21,1077.43,10.7743,4.052099e+11,2.253460e+10,4.949871e+10,9.984292e+09,17996.83,21019.21,17996.83
926,2023-01-19,bitcoin,20726.84,-429.94,-4.2994,3.993496e+11,-8.055541e+09,4.061206e+10,7.333216e+09,20853.23,21175.34,20726.84
...,...,...,...,...,...,...,...,...,...,...,...,...
6580,2023-08-03,solana,23.13,-0.80,-0.0080,9.376126e+09,-2.875034e+08,4.269454e+08,-6.984695e+06,23.76,23.93,23.13
6581,2023-08-07,solana,23.16,0.53,0.0053,9.384286e+09,2.287942e+08,3.381710e+08,8.180034e+07,22.65,23.16,22.63
6582,2023-08-11,solana,24.62,0.24,0.0024,9.982519e+09,8.782001e+07,3.521246e+08,-1.059151e+08,23.05,24.62,23.05
6583,2023-08-15,solana,25.15,0.93,0.0093,1.021132e+10,3.717702e+08,3.880259e+08,1.098438e+08,24.58,25.15,24.22
6584,2023-08-19,solana,21.33,-0.32,-0.0032,8.681696e+09,-1.516802e+08,4.122202e+08,-2.441924e+08,23.88,23.88,21.33